name: Build & Push Frontend Image
# test hÄ‘ong repo k8s-3-4 - 5 - 6
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: jobquest-ptud-hai-481413

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: jobquest-ptud-hai-481413

    - name: Configure Docker
      run: |
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

    - name: Build & Push Frontend
      run: |
        IMAGE=asia-southeast1-docker.pkg.dev/jobquest-ptud-hai-481413/jobquest-repo/frontend:${GITHUB_SHA}
        docker build -t $IMAGE .
        docker push $IMAGE

    # Trigger k8s repo workflow
    - name: Trigger k8s workflow
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PAT }}
        repository: lma273/jobquest-k8s
        event-type: update-deploy
        client-payload: |
          {
          "frontend_tag": "${{ github.sha }}"
          }
